from selenium.webdriver.common.by import By

search_field = (By.XPATH, "//*[@id='twotabsearchtextbox']")
submit_search = (By.XPATH, "//*[@id='submit_search']")
lot_price = (By.XPATH, "//span[@id='lot-price']")
auction_fee = (By.XPATH, "//span[@id='auction-fees']")
shoe_colors = (By.XPATH, "//*[contains(@class,'s-color-swatch-inner-circle-fill')]")
shoe_details = (By.XPATH, "//*[contains(@class,'a-size-base-plus a-color-base a-text-normal')]")
shoe_heading = (By.XPATH, "//*[@id='productTitle']")
shoe_size_heading = (By.XPATH, "//*[@id='inline-twister-expanded-dimension-text-size_name']")
first_shoe_size = (By.XPATH, "//*[@id='size_name_0']/span/input")
first_shoe_size_heading = (By.XPATH, "//*[@id='size_name_0-announce']/div[1]/span")
price_heading = (By.XPATH, "//*[@id='corePrice_feature_div']/div/span/span[2]/span[2]")
price_decimal_fraction = (By.XPATH, "//*[@id='corePrice_feature_div']/div/span/span[2]/span[3]")
change_address = (By.XPATH, "//*[@id='nav-main']/div[1]/div/div/div[3]/span[2]/span/input")
location_input_field = (By.XPATH, "//*[@id='GLUXZipUpdateInput']")
location_update_submit_button = (By.XPATH, "//*[@id='GLUXZipUpdate']")
location_updated_continue_button = (By.XPATH, "//*[@id='GLUXConfirmClose-announce']")
add_to_cart_button = (By.XPATH, "//*[@id='add-to-cart-button']")
cart_page_price = (By.XPATH, "//*[@id='sw-subtotal']/span[2]/span/span[2]/span[2]")
